Controllers/AdminController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebProgramlamaProje.Data;
using WebProgramlamaProje.Models;

namespace WebProgramlamaProje.Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<User> userManager;

        public AdminController(ApplicationDbContext context, UserManager<User> um)
        {
            _context = context;
            userManager = um;
        }
        [Route("adminpanel")]
        public async Task<IActionResult> IndexAsync()
        {
            var user = await userManager.FindByNameAsync(User.Identity.Name);
            if (!await userManager.IsInRoleAsync(user, "admin"))
            {
                return Forbid();
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateRole(string roleName)
        {
            var user = await userManager.FindByNameAsync(User.Identity.Name);
            if (!await userManager.IsInRoleAsync(user, "admin"))
            {
                return Forbid();
            }
            _context.Roles.Add(new Microsoft.AspNetCore.Identity.IdentityRole()
            {
                Name = roleName,
                NormalizedName = roleName,
            });
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> AddRoleToUser(string roleName, string username)
        {
            var user = await userManager.FindByNameAsync(username);
            if(!await userManager.IsInRoleAsync(user, roleName) && user != null)
            {
                var r = await userManager.AddToRoleAsync(user, roleName);
                _context.SaveChanges();
            }
            
            return RedirectToAction("Index");
        }
    }
}

Controllers/ProfileController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using WebProgramlamaProje.Data;
using WebProgramlamaProje.Models;
using Microsoft.Extensions.Localization;

namespace WebProgramlamaProje.Controllers
{
    public class ProfileController : Controller
    {
        private UserManager<User> userManager;
        private readonly ApplicationDbContext _context;
        private readonly IStringLocalizer<ProfileController> _localizer;
        private DbQueryFunc funcs;

        public ProfileController(UserManager<User> userManager, ApplicationDbContext context, IStringLocalizer<ProfileController> loc)
        {
            this.userManager = userManager;
            _context = context;
            _localizer = loc;
            funcs = new DbQueryFunc(_context);
        }

        [Route("{username}")]
        public IActionResult Index(string username)
        {
            User user = userManager.Users.Where(x => x.UserName == username).FirstOrDefault();
            ViewBag.username = user.UserName;
            var result = funcs.GetInfoWhereUser(user).Take(4);
            var reviews = funcs.GetInfoWhereUserReviewNotNull(user).Take(2);
            dynamic model = new System.Dynamic.ExpandoObject();
            model.act = result;
            model.rev = reviews;
            return View(model);
        }

        [Route("{username}/films")]
        public IActionResult Films(string username)
        {
            User user = userManager.Users.Where(x => x.UserName == username).FirstOrDefault();
            ViewBag.username = user.UserName;
            var result = funcs.GetInfoWhereUser(user);
            return View(result);
        }

        [Route("{username}/reviews")]
        public IActionResult Reviews(string username)
        {
            User user = userManager.Users.Where(x => x.UserName == username).FirstOrDefault();
            ViewBag.username = user.UserName;
            var result = funcs.GetInfoWhereUserReviewNotNull(user);
            return View(result);
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebProgramlamaProje.Models;
using Microsoft.AspNetCore.Http;
using WebProgramlamaProje.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;


namespace WebProgramlamaProje.Controllers
{
    
    public class UserController : Controller
    {
        private UserManager<User> userManager;
        private SignInManager<User> signinManager;
        private readonly ILogger<UserController> _logger;

        public UserController(UserManager<User> context, SignInManager<User> signin, ILogger<UserController> logger)
        {
            userManager = context;
            signinManager = signin;
            _logger = logger;
        }
        [HttpPost]
        public async Task<IActionResult> Signup(RegisterModel model)
        {
            if (User.Identity.IsAuthenticated) { return Redirect("../Home/Index"); }

            if (ModelState.IsValid)
            {
                User user = new User()
                {
                    Name = model.Name,
                    UserName = model.UserName,
                    Email = model.Email,
                    EmailConfirmed = true,
                };
                var result = await userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    var currentUser = await userManager.FindByNameAsync(user.UserName);
                    var roleResult = await userManager.AddToRoleAsync(currentUser,"user");
                    return RedirectToAction("Signin");
                }
                else
                {
                    foreach (var i in result.Errors)
                    {
                        ModelState.AddModelError("", i.Description);
                    }
                }
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Signup()
        {
            if (User.Identity.IsAuthenticated) { return Redirect("../Home/Index"); }
            return View();
        }
        [HttpGet]
        public IActionResult Signin()
        {
            if (User.Identity.IsAuthenticated) { return Redirect("../Home/Index"); }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Signin(LoginModel model)
        {
            if (User.Identity.IsAuthenticated) { return Redirect("../Home/Index"); }

            Console.WriteLine("asdsadsad - " + ModelState.IsValid);
            if (ModelState.IsValid)
            {
                var result = await signinManager.PasswordSignInAsync(model.UserName, model.Password, true, lockoutOnFailure: false);
                Console.WriteLine("result  " + result);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return Redirect("../Home/Index");
                }
            }
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await signinManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            return Redirect("../Home/Index");//Homepage git.
        }
    }
}

Views/Shared/_Layout.cshtml
@inject IViewLocalizer Localizer
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proje</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <script src="https://kit.fontawesome.com/df18e69f5a.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light header-bg header-font box-shadow">
            <div class="container max-width-950">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Proje</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        @{ if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <label class="switch m-0">
                                        <input id="local" type="checkbox" value="tr">
                                        <span class="slider round"></span>
                                    </label><b>TR</b>
                                </li>
                                <li class="nav-item">
                                    <a class="" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                                </li>
                                <li class="nav-item">
                                    <a class="" asp-area="" asp-controller="Profile" asp-action="Index" asp-route-username="@User.Identity.Name">@Localizer["Profile"]</a>
                                </li>
                                <li class="nav-item">
                                </li>
                                <li class="nav-item">
                                    <a class="" asp-area="" asp-controller="User" asp-action="Logout">@Localizer["Logout"]</a>
                                </li>
                                @if (User.IsInRole("admin"))
                                {
                                    <li class="nav-item">
                                        <a class="" asp-area="" asp-controller="Admin" asp-action="Index">ADMIN PANEL</a>
                                    </li>
                                }
                                <li class="nav-item">
                                    <button type="button" data-toggle="modal" data-target="#exampleModal" class="badge-log">
                                        <i class="fas fa-plus mr-2"></i>@Localizer["Search"]
                                    </button>
                                </li>

                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="" asp-area="" asp-controller="User" asp-action="Signin">SIGN IN</a>
                                </li>
                                <li class="nav-item">
                                    <a class="" asp-area="" asp-controller="User" asp-action="Signup">CREATE ACCOUNT</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="content">
        <div class="container max-width-950">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
    <footer class="footer text-muted footer">
        <div class="container max-width-950">
            &copy; 2020 - Proje
        </div>
    </footer>

    <!-- Search Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content modal-bg-color pt-3 pb-3 pl-4 pr-4">
                <div class="modal-header border-0 modal-header-font">
                    <h5 class="modal-title" id="exampleModalLabel">search movie</h5>
                    <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="get" action="/">
                        <input id="search-input" type="text" class="form-control" placeholder="Million Dollar Baby..." />
                        <div id="dropdown-search" class="search-dropdown">
                            <ul id="movie-list"></ul>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

<script>
    $(document).ready(function () {

        var url = window.location.href.split('?')[1]
        if (url == 'culture=tr&ui-culture=tr') {
            $('#local').prop('checked', true);
        }

        $('#search-input').keyup(function (e) {
            $('#movie-list').html('');
            $.ajax({
                type: 'GET',
                url: "@Url.Action("SearchMovie","Home")" + "?movie=" + $('#search-input').val(),
                dataType: 'json',
                success: function (data) {
                    $.each(data, function (index, element) {
                        $('#movie-list').append(
                            "<a href=\"../movie/" + element.movieID + "\"><li><span>" + element.title + "(" + element.year + ") </span><small>" + element.director + "</small></li></a>"
                        );
                    })
                },
                error: function () {
                    window.alert("Hata");
                }
            });
            $('#dropdown-search').show("fast");
        });

        $('#local').click(function () {
            var url = window.location.href.split('?')[0];
            var culture;
            if ($('#local').is(":checked")) {
                culture = "?culture=tr&ui-culture=tr";
            }
            else {
                culture = "?culture=en-US&ui-culture=en-US";
            }
            window.location.href = url + culture;
        });
    });

        
</script>
</body>
</html>